import Head from "next/head";
import React from "react";

type Props = {};

const Plans = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <img
          src="/images/icon.svg"
          alt="Netflix logo"
          width={100}
          height={100}
          className="cursor-pointer object-contain"
        />
      </header>
    </div>
  );
};

export default Plans;
